apiVersion: v1
kind: Pod
metadata:
  name: hello-target
  labels:
    app: hello-target

spec:
  containers:
  - image: docker.io/alishagupta/hello:firttry
    name : hello-target
    imagePullPolicy: Always
    env:
    - name: ENABLE_CUSTOM_METRICS
      value: "true"
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "50Mi"
      requests:
        cpu: 200m
    ports:
    - containerPort: 80


