apiVersion: v1
kind: ReplicationController
metadata:
  name: hellorep
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: hellorep
      labels:
        app: nginx
    spec:
      containers:
      - name: demo
        image: docker.io/alishagupta/hello:firttry
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m

